# Generated by Django 4.2.11 on 2024-03-11 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, verbose_name='Names')),
                ('last_name', models.CharField(max_length=60, verbose_name='Lastnames')),
                ('job', models.CharField(choices=[('0', 'Counter'), ('1', 'Administrator'), ('2', 'Economist'), ('3', 'Developer')], max_length=1, verbose_name='Job')),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departament.departament')),
            ],
        ),
    ]
