# Generated by Django 4.2.11 on 2024-03-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_remove_employee_skill_employee_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='skill',
            field=models.ManyToManyField(to='employees.skill'),
        ),
    ]
