# Generated by Django 4.2.11 on 2024-03-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.CharField(max_length=30, verbose_name='Skills'),
        ),
    ]
