# Generated by Django 4.2.11 on 2024-03-19 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departament', '0002_alter_departament_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departament',
            old_name='shor_name',
            new_name='shorname',
        ),
    ]
