# Generated by Django 4.2.11 on 2024-03-12 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('probes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prueba',
            old_name='titulo',
            new_name='mes',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='subtitulo',
            new_name='meta',
        ),
        migrations.AlterUniqueTogether(
            name='prueba',
            unique_together={('mes',)},
        ),
    ]
